## One command for a complete application or a registered typed CRUD resource.
import std/[os, strutils, json]
import ./[core, project, scaffold_types, scaffold_files, scaffold_templates, scaffold_model_templates, scaffold_model_pages]
export scaffold_types

const
  ScaffoldSchema = 2
  ManifestPath = ".leaf/scaffold.json"
  PagesPath = "app/generated/pages.nim"
  RoutesPath = "config/generated/routes.nim"
  MigrationsPath = "app/generated/migrations.nim"
  GeneratedHeader = "# Generated by leaf scaffold. Do not edit this file.\n"
  Templates = [
    ("main.nim", staticRead("templates/scaffold/main.nim")),
    ("app/application.nim", staticRead("templates/scaffold/application.nim")),
    ("app/shell.nim", staticRead("templates/scaffold/shell.nim")),
    ("app/components/empty_state.nim", staticRead("templates/scaffold/empty_state.nim")),
    ("app/pages/home/page.nim", staticRead("templates/scaffold/home_page.nim")),
    ("app/pages/home/logic.nim", staticRead("templates/scaffold/home_logic.nim")),
    ("app/pages/home/views/list.nim", staticRead("templates/scaffold/home_list.nim")),
    ("app/pages/home/views/index.nim", staticRead("templates/scaffold/home_index.nim")),
    ("app/pages/home/views/search.nim", staticRead("templates/scaffold/home_search.nim")),
    ("app/pages/home/views/settings.nim", staticRead("templates/scaffold/home_settings.nim")),
    ("config/routes.nim", staticRead("templates/scaffold/routes.nim")),
    ("README.md", staticRead("templates/scaffold/README.md"))]

proc pageRegistry(resources: seq[ResourceSpec], schema: int): string =
  result = GeneratedHeader & "import leaf\n"
  if schema == 1: result.add("import leaf/sqlite as storage\n")
  result.add("import ../pages/home/page as home_page\n")
  for resource in resources:
    result.add("import ../pages/" & resource.plural & "/page as " & resource.plural & "_page\n")
  if schema == 1:
    result.add("\nproc generatedPages*(database: storage.Database): seq[PageDefinition] =\n  @[home_page.definition(database)")
    for resource in resources: result.add(",\n    " & resource.plural & "_page.definition(database)")
  else:
    result.add("\nproc generatedPages*(): seq[PageDefinition] =\n  @[home_page.definition()")
    for resource in resources: result.add(",\n    " & resource.plural & "_page.definition()")
  result.add("]\n")

proc migrationRegistry(resources: seq[ResourceSpec]): string =
  result = GeneratedHeader & "import leaf/sqlite\n\nconst\n"
  let task = parseResource("Task", @["title:string", "done:bool"], 1)
  for resource in @[task] & resources:
    let name = align($resource.migration, 3, '0') & "_create_" & resource.plural
    result.add("  migrationSql" & $resource.migration & " = staticRead(\"../../db/migrations/" & name & ".up.sql\")\n")
  result.add("\nproc generatedMigrations*(): seq[Migration] =\n  @[\n")
  for i, resource in @[task] & resources:
    if i > 0: result.add(",\n")
    let name = align($resource.migration, 3, '0') & "_create_" & resource.plural
    result.add("    Migration(version: " & $resource.migration & ", name: " & name.escape &
      ", sql: migrationSql" & $resource.migration & ")")
  result.add("\n  ]\n")

proc routeRegistry(resources: seq[ResourceSpec]): string =
  result = GeneratedHeader & "import leaf\n\nproc generatedRoutes*(): seq[Route] =\n  @[\n    Route(name: \"home\", path: \"/\", page: \"home\", view: \"index\"),\n    Route(name: \"search\", path: \"/search\", page: \"home\", view: \"search\"),\n    Route(name: \"settings\", path: \"/settings\", page: \"home\", view: \"settings\")"
  for resource in resources:
    let p = resource.plural
    result.add(",\n    Route(name: \"" & p & "\", path: \"/" & p & "\", page: \"" & p & "\", view: \"index\")")
  result.add("\n  ]\n")

proc manifest(resources: seq[ResourceSpec], schema: int): string =
  var entries = newJArray()
  for resource in resources:
    var fields = newJArray()
    for field in resource.fields: fields.add(%*{"name": field.name, "type": field.kind})
    entries.add(%*{"model": resource.model, "singular": resource.singular,
      "fields": fields, "migration": resource.migration})
  var value = %*{"schema": schema, "resources": entries}
  if schema == 2:
    value["model_api"] = %1
    value["timestamps"] = %true
  pretty(value) & "\n"

proc member(value: JsonNode, name: string, kind: JsonNodeKind): JsonNode =
  if value.kind != JObject or name notin value or value[name].kind != kind:
    fail("invalid scaffold manifest field: " & name)
  value[name]

proc checkResource(resources: seq[ResourceSpec], resource: ResourceSpec) =
  if identity(resource.model) == "task": fail("Task already exists in the home example")
  if resource.plural == "leaf_schema_migrations" or resource.plural.startsWith("sqlite_"):
    fail("resource table name is reserved by SQLite storage: " & resource.plural)
  if resource.plural in ["home", "search", "settings"]: fail("resource route conflicts with a built-in route")
  for prior in resources:
    if identity(prior.model) == identity(resource.model) or prior.plural == resource.plural or
        prior.singular == resource.singular:
      fail("resource already exists: " & resource.model)
    if prior.migration == resource.migration: fail("duplicate migration version")

proc loadManifest(root: string): ScaffoldManifest =
  let path = guardedPath(root, ManifestPath)
  if not fileExists(path):
    fail("resource generation needs a scaffold application; create one with leaf g scaffold DIRECTORY")
  let value = parseFile(path)
  result.schema = member(value, "schema", JInt).getInt
  if result.schema notin [1, 2]: fail("unsupported scaffold manifest schema")
  if result.schema == 2:
    if member(value, "model_api", JInt).getInt != 1 or not member(value, "timestamps", JBool).getBool:
      fail("unsupported scaffold model metadata")
  let entries = member(value, "resources", JArray)
  for entry in entries:
    let name = member(entry, "model", JString).getStr
    let singular = member(entry, "singular", JString).getStr
    var fields: seq[string]
    for field in member(entry, "fields", JArray):
      fields.add(member(field, "name", JString).getStr & ":" & member(field, "type", JString).getStr)
    let version = member(entry, "migration", JInt).getInt
    if version < 2 or version >= high(int): fail("invalid scaffold migration version")
    let resource = parseResource(singular, fields, version)
    if name != resource.model or singular != resource.singular:
      fail("noncanonical resource identity in scaffold manifest")
    if result.schema == 2: checkModelFields(resource)
    checkResource(result.resources, resource)
    result.resources.add(resource)
  for file in [ScaffoldFile(path: PagesPath, content: pageRegistry(result.resources, result.schema)),
      ScaffoldFile(path: RoutesPath, content: routeRegistry(result.resources)),
      ScaffoldFile(path: MigrationsPath, content: migrationRegistry(result.resources))]:
    let registered = guardedPath(root, file.path)
    if not fileExists(registered) or readFile(registered) != file.content:
      fail("generated registry was modified or is missing: " & file.path)

proc appFiles(name: string): seq[ScaffoldFile] =
  const
    modelApplication = staticRead("templates/scaffold/model_application.nim")
    modelPage = staticRead("templates/scaffold/model_home_page.nim")
    modelLogic = staticRead("templates/scaffold/model_home_logic.nim")
    modelReadme = staticRead("templates/scaffold/model_README.md")
  for (path, content) in Templates:
    var selected = content
    case path
    of "app/application.nim": selected = modelApplication
    of "app/pages/home/page.nim": selected = modelPage
    of "app/pages/home/logic.nim": selected = modelLogic
    of "README.md": selected = modelReadme
    else: discard
    result.add(ScaffoldFile(path: path, content: selected.replace("{{name}}", name)))
  result.add(ScaffoldFile(path: "config.nims", content: "import std/strutils\nimport leaf/orm_config\nfor argument in ormCompilerArgs(OrmSourceRoot):\n  let pair = argument.split(\":\", 1)\n  switch(pair[0].strip(chars = {'-'}), pair[1])\n"))
  result.add(ScaffoldFile(path: "app/models/application_record.nim", content: "import leaf/model\n\ntype ApplicationRecord* = ref object of TimestampedRecord\ndefineAbstractModel(ApplicationRecord)\n"))
  result.add(ScaffoldFile(path: "leaf.json", content: pretty(newProjectConfig(name, "main.nim",
    @["main.nim", "app", "config", "db", "assets"])) & "\n"))
  result.add(ScaffoldFile(path: ".gitignore", content: "/target/\n/dist/\n*.core\n"))
  result.add(ScaffoldFile(path: "assets/message.txt", content: "Leaf page-group application\n"))
  result.add(ScaffoldFile(path: "config/application.nim", content:
    "const\n  ApplicationTitle* = " & name.escape & "\n  WindowWidth* = 960\n  WindowHeight* = 640\n"))
  result.add(ScaffoldFile(path: "config/database.nim", content:
    "## Importing configuration does not open storage; application startup does.\nimport std/os\nimport leaf/sqlite\nimport ../app/generated/migrations\nexport sqlite\n\nproc databasePath*(): string =\n  getEnv(\"LEAF_DATABASE_PATH\", getDataDir() / " & name.escape & " / \"application.sqlite3\")\n\nproc openApplicationDatabase*(path = databasePath()): Database =\n  result = openDatabase(path)\n  try:\n    result.migrate(generatedMigrations())\n  except CatchableError:\n    result.close()\n    raise\n"))
  let task = parseResource("Task", @["title:string", "done:bool"], 1)
  result.add(ScaffoldFile(path: "app/models/task.nim", content: modelCodeV2(task)))
  result.add(ScaffoldFile(path: "tests/test_home.nim", content: modelTestCodeV2(task)))
  result.add(migrationFilesV2(task))
  result.add(ScaffoldFile(path: PagesPath, content: pageRegistry(@[], ScaffoldSchema)))
  result.add(ScaffoldFile(path: RoutesPath, content: routeRegistry(@[])))
  result.add(ScaffoldFile(path: MigrationsPath, content: migrationRegistry(@[])))
  result.add(ScaffoldFile(path: ManifestPath, content: manifest(@[], ScaffoldSchema)))

proc generateScaffold*(options: ScaffoldOptions): seq[string] =
  let newProject = options.project.len == 0
  var root: string
  var plan: seq[ScaffoldFile]
  if newProject:
    if options.fields.len > 0: fail("resource fields require --project DIRECTORY")
    root = normalizedPath(absolutePath(options.target))
    plan = appFiles(root.extractFilename)
  else:
    root = readProject(options.project).root
    let loaded = loadManifest(root)
    var resources = loaded.resources
    let schema = loaded.schema
    var version = 2
    for resource in resources: version = max(version, resource.migration + 1)
    let resource = parseResource(options.target, options.fields, version)
    checkResource(resources, resource)
    if schema == 1:
      plan = resourceFiles(resource)
      plan.add(migrationFiles(resource))
      plan.add(ScaffoldFile(path: "tests/test_" & resource.plural & ".nim", content: testCode(resource)))
    else:
      plan = resourceFilesV2(resource)
      plan.add(migrationFilesV2(resource))
      plan.add(ScaffoldFile(path: "tests/test_" & resource.plural & ".nim", content: modelTestCodeV2(resource)))
    resources.add(resource)
    for file in [ScaffoldFile(path: PagesPath, content: pageRegistry(resources, schema)),
        ScaffoldFile(path: RoutesPath, content: routeRegistry(resources)),
        ScaffoldFile(path: MigrationsPath, content: migrationRegistry(resources)),
        ScaffoldFile(path: ManifestPath, content: manifest(resources, schema))]:
      var updated = file
      updated.update = true
      updated.previous = readFile(guardedPath(root, file.path))
      plan.add(updated)
  checkPlan(root, plan, newProject)
  for file in plan:
    result.add((if file.update: "update " else: "create ") & file.path)
  if not options.dryRun: writePlan(root, plan, newProject)
